apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: kafka
spec:
 authentication:
    type: scram-sha-512
 authorization:
    acls: []
    type: simple
