apiVersion: apps/v1 
kind: StatefulSet 
metadata: 
  name: test-pod
  labels: 
    app: test-pod
spec: 
  replicas: 1
  serviceName: ""
  selector: 
    matchLabels:
      app: test-pod
  template: 
    metadata:
      labels: 
        app: test-pod 
    spec:
      serviceAccountName: bigdata
      imagePullSecrets:
      - name: regcred
      containers:
      - name: testpod
        image: ubuntu
        env:
        - name: http_proxy
          value: http://proxy1.safaricomet.net:3128 
        - name: https_proxy
          value: http://proxy1.safaricomet.net:3128 
        command: ["/bin/sleep", "3650d"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/bitnami/kafka"
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: airflow-dags
# apiVersion: v1
# kind: Service
# metadata:
  # labels:
    # app: test-pod
  # name: copypodservice
# spec:
  # ports:
  # - name: copy
    # port: 5432
    # protocol: TCP
    # targetPort: 5432
  # selector:
    # app: test-pod
  # type: ClusterIP