---  
# Jupyter Hub Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jupyterhub-ingress
  labels:
    name: jupyterhub-ingress
  annotations: 
     ingress.kubernetes.io/rewrite-target: /
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_headers "X-Frame-Options: SAMEORIGIN";
       more_set_headers "X-XSS-protection: 1";
       more_set_headers "X-Content-Type-Options: nosniff";
       more_set_headers "Access-Control-Allow-Origin: accept, content-type, authorization";

spec:
  rules:
  - host: jupyterhub.big-data2.safaricomet.net
    http:
      paths:
      - path: /
        backend:
            serviceName: jupyterhub-service
            servicePort: 8000
        pathType: ImplementationSpecific
