{{- if .Values.ingress.hbase.enabled -}}
# HBase Master UI Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hadoop.fullname" . }}-hbase-ingress
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
  annotations: 
     ingress.kubernetes.io/rewrite-target: /
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.hbase.host }}
    http:
      paths:
      - path: /
        backend:
            serviceName: {{ include "hadoop.fullname" . }}-hdfs-nn
            servicePort: 16010
        pathType: ImplementationSpecific
{{- end -}}
