{{- if .Values.ingress.nameNode.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-nn-ingress
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: hdfs-nn
  annotations: 
     ingress.kubernetes.io/rewrite-target: /
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{.Values.ingress.nameNode.host}}
    http:
      paths:
      - path: /
        backend:
            serviceName: {{ include "hadoop.fullname" . }}-hdfs-nn
            servicePort: 9870
        pathType: ImplementationSpecific
{{- end -}}