apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-validity-expiry-alerts
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-device-change
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-airtime-depletion
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-airtime-usage
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-bundle-balance
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-consumption-alerts
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-voice-endof-call-notifications
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-data-endof-session-notifications
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: ncc-recharge
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: 6d-customer-activations
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 259200000
    segment.bytes: 1073741824