apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
   name: ncc        
   labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: ncc-
        patternType: prefix
        type: topic

    - host: '*'
      operation: Read
      resource:
        name: ncc-
        patternType: prefix
        type: topic
    
    - host: '*'
      operation: Read
      resource:
        name: ncc-recharge-cg
        patternType: literal
        type: group        

    type: simple