apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-ca.fullname" . }}
  namespace: {{ default "default" .Values.global.namespace }}
  labels:
    {{- include "nifi-ca.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nifi-ca.selectorLabels" . | nindent 4 }}