{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spark.name" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/component: spark
    {{- include "spark.labels" . | nindent 4 }}
  annotations: 
     ingress.kubernetes.io/rewrite-target: /
     kubernetes.io/ingress.class: nginx
spec:
  rules:
    {{- if .Values.ingress.hostname }}
    {{- toYaml .Values.ingress.hostPaths | nindent 10 }}
    {{- end }}
{{- end -}}