apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name:  kafka-connect
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
   strimzi.io/use-connector-resources: "true"
spec:
  version: 3.0.0
  replicas: 3
  bootstrapServers: kafka-kafka-0:9094,kafka-kafka-1:9094,kafka-kafka-2:9094
  authentication:
    type: scram-sha-512
    username: admin
    passwordSecret:
      secretName: admin
      password: password
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1

  build:
    output:
      type: docker
      additionalKanikoOptions:
      - --skip-tls-verify
      - --verbosity=info
      # - --build-arg "http_proxy=http://proxy1.safaricomet.net:3128"
      # - --build-arg "HTTP_PROXY=http://proxy1.safaricomet.net:3128"
      # - --build-arg "https_proxy=http://proxy1.safaricomet.net:3128"
      # - --build-arg "HTTPS_PROXY=http://proxy1.safaricomet.net:3128"
      image: et01-harbor.safaricomet.net/bigdata/blueprint-connect-cluster:latest
      pushSecret: regcred
    plugins: 
      - name: splunk-connector
        artifacts:
          - type: jar
            fileName: splunk
            url: https://github.com/splunk/kafka-connect-splunk/releases/download/v2.0.9/splunk-kafka-connect-v2.0.9.jar
            sha512sum: 14e793bebf7f0b196884b68c68cc7ac7a8c80cedcb8bb296af57781f8ad5450f3d6d45f60abebaf5310a46cdc2fa85e01a20f8bff4ce66e94cb180002f8127c5
      - name: jdbc-connector
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven/
            group: io.confluent
            artifact: kafka-connect-jdbc
            version: 10.4.0
      - name: elasticsearch-connector
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven/
            group: io.confluent
            artifact: kafka-connect-elasticsearch
            version: 11.1.10
  template:
    pod:
      imagePullSecrets:
        - name: regcred

  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"