apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
   name: cps        
   labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: cps_
        patternType: prefix
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: cps_
        patternType: prefix
        type: topic
    type: simple

# org.apache.kafka.common.security.scram.ScramLoginModule required username="mpesa" password="KBAgU9iqHseQ"; DC1
# org.apache.kafka.common.security.scram.ScramLoginModule required username="mpesa" password="eO91s3qAvNgs"; DC2



# kubectl get secret kafka-cluster-ca-cert -o jsonpath='{.data.ca\.p12}' | base64 -d > ca.p12
# kubectl get secret kafka-cluster-ca-cert -o jsonpath='{.data.ca\.password}' | base64 -d > ca.password


# kubectl get secret mpesa -o jsonpath='{.data.user\.p12}' | base64 -d > user.p12
# kubectl get secret mpesa -o jsonpath='{.data.user\.password}' | base64 -d > user.password