apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
   name: cps        
   labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: cps_
        patternType: prefix
        type: topic

    type: simple

# org.apache.kafka.common.security.scram.ScramLoginModule required username="mpesa" password="KBAgU9iqHseQ"; DC1
# org.apache.kafka.common.security.scram.ScramLoginModule required username="mpesa" password="eO91s3qAvNgs"; DC2