apiVersion: v1
kind: Namespace
metadata:
  name: bigdata-unison
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:privileged
  namespace: bigdata-unison
rules:
- apiGroups: [policy]
  resources: [podsecuritypolicies]
  resourceNames: [vmware-system-privileged]
  verbs: [use]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:psp:privileged
  namespace: bigdata-unison
subjects:
- kind: ServiceAccount
  name: default
  namespace: bigdata-unison
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  unison
  namespace: bigdata-unison
  labels:
    app:  unison
spec:
  selector:
    matchLabels:
      app: unison
  replicas: 1
  template:
    metadata:
      labels:
        app:  unison
    spec:
      containers:
      - name:  unison-app
        image:  et02-harbor.safaricomet.net/library/unison:2.52.1
        command:
          - unison
        args:
          - -batch
          - -auto
          - -repeat=watch
          - -group
          - -owner
          - /dfs
          - socket://10.3.41.67:5000//dfs
          - -path=name
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 4000Mi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: dfs
          mountPath: /dfs/name
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Africa/Addis_Ababa
      - name: dfs
        persistentVolumeClaim:
          claimName: unison-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: unison-test
spec:
   accessModes:
       - ReadWriteMany
   storageClassName: nfs-bigdata
   volumeMode: Filesystem
   resources:
       requests:
          storage: 5Gi