{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hive.name" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/component: hive
    {{- include "hive.labels" . | nindent 4 }}
  annotations: 
     ingress.kubernetes.io/rewrite-target: /
     kubernetes.io/ingress.class: nginx
spec:
  rules:
    {{- toYaml .Values.ingress.hostPaths | nindent 10 }}
{{- end -}}