---
# NiFi Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nifi-registry
  namespace: et01-tkg-bigdata-prod
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app: nifi-registry
  serviceName: nifi-registry
  template:
    metadata:
      labels:
        app: nifi-registry
    spec:
      serviceAccountName: bigdata
      containers:
      - name: nifi-registry
        image: "kapkiai/nifi-registry:1.15.1"
        imagePullPolicy: IfNotPresent
        command: 
        - sh
        - -c
        - |
          cat /opt/nifi-registry/nifi-registry-current/conf/providers.tmp > /opt/nifi-registry/nifi-registry-current/conf/providers.xml
          /opt/nifi-registry/scripts/start.sh
        resources: 
          requests:
            cpu: "1"
            memory: "2Gi"
            ephemeral-storage: "2Gi"
          limits:
            cpu: "2"
            memory: "3Gi"
            ephemeral-storage: "3Gi"
        ports:
        - containerPort: 18443
          name: http-port
        - containerPort: 22
          name: ssh
        # - containerPort: 9088
        #   name: cluster
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NIFI_REGISTRY_WEB_HTTPS_PORT
          value: "18443"  
        - name: NIFI_REGISTRY_WEB_HTTPS_HOST
          value: $(HOSTNAME).nifi-registry.tkg-bigdata-ns.svc.cluster.local
# I have tried documenting some configs here. Configs that are nifi related can be read from official nifi documenation and changes 
# effected to this configurations
          # LDAP Integration
        - name: AUTH
          value: "ldap" 
        - name: NIFI_ANALYTICS_PREDICT_ENABLED
          value: "true"
        - name: LDAP_AUTHENTICATION_STRATEGY
          value: SIMPLE
        - name: LDAP_MANAGER_DN
          value: CN=Bigdata Service Account,OU=Service Accounts,OU=Domain Users,DC=safaricomet,DC=net
        - name: LDAP_MANAGER_PASSWORD
          value: lyOdmSBwCsZnD4dLnOAE
        - name: LDAP_URL
          value: ldap://safaricomet.net:389
        - name: LDAP_USER_SEARCH_BASE
          value: OU=BigData Users,OU=Domain Users,DC=safaricomet,DC=net
        - name: LDAP_USER_SEARCH_FILTER
          value: (sAMAccountName={0})
        - name: LDAP_IDENTITY_STRATEGY
          value: USE_USERNAME
        # - name: NIFI_REGISTRY_DB_URL
          # value: jdbc:postgresql://hive-postgresql-headless:5432/nifireg
        # - name: NIFI_REGISTRY_DB_CLASS
          # value: org.postgresql.Driver
        # - name: NIFI_REGISTRY_DB_DIR
          # value: /opt/nifi-registry/jars
        # - name: NIFI_REGISTRY_DB_USER
          # value: hive
        # - name: NIFI_REGISTRY_DB_PASS
          # value: hive

          # CA Configs
        # - name: NIFI_CA_HOST    #NiFI CA as specified in CA server. default one is 'nifi-ca-cs', hostname for ca server. Make sure it marches with ca server
        #   value: nifi-ca-cs 
        - name: TOKEN     # Token to get cert from CA. Useful to prevent MITM attacks
          value: "1234578912345678912" 
        - name: OU    # You desired OU to generate certificates
          value: "BIGDATA"   
        - name: NAMESPACE # NiFi namespace, used in building nifi CA OU urls. Note: service name must be 'nifi'
          value: et01-tkg-bigdata-prod          
          # With our own CA server/client set up, the commented configs below are unnecessary
        - name: KEYSTORE_PATH
          value: "./conf/keystore.jks"
        - name: KEYSTORE_TYPE
          value: "jks"
        - name: TRUSTSTORE_PATH
          value: "./conf/truststore.jks"
        - name: TRUSTSTORE_TYPE
          value: "jks"

        - name: INITIAL_ADMIN_IDENTITY
          value: "Alphonce-BI" 
        - name: NIFI_WEB_PROXY_HOST  # Important when accessing nifi via LB/nodeIP else nifi will reject you
          value: "nifi-registry.big-data.safaricomet.net"

        volumeMounts:
          - mountPath: /opt/nifi-registry/nifi-registry-current/database
            name: database
          - mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
            name: flow-storage
          - mountPath: /opt/nifi-registry/nifi-registry-current/auth_conf
            name: auth
          - mountPath: /opt/nifi-registry/nifi-registry-current/logs
            name: logs
          # - mountPath: /opt/nifi-registry/nifi-registry-current/conf/providers.tmp
            # name: providers
            # subPath: providers.tmp
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: 2Gi
          name: logs    
        # - name: "providers"
          # configMap:
            # name: nifiregproviders
            # items:
              # - key: "nifiregproviders.xml"
                # path: "providers.tmp"


  volumeClaimTemplates:
  - metadata:
      name: database
    spec:
      storageClassName: topology-aware-standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 12Gi
  - metadata:
      name: flow-storage
    spec:
      storageClassName: topology-aware-standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 12Gi
 
  - metadata:
      name: auth
    spec:
      storageClassName: nfs-bigdata
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
        