apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-response-headers: x-username, x-groups
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header Ldap-Allowed-Groups "bigdataadmins, Bigdata Users, ET-RDS-Users";
    nginx.ingress.kubernetes.io/auth-url: https://nginx-ldap.ingress-nginx.svc.cluster.local/auth
    nginx.ingress.kubernetes.io/server-snippet: |
      error_page 401 = @login;
      location @login {
        return 302 https://nginx-ldap.big-data2.safaricomet.net/?protocol=$pass_access_scheme&callback=$host;
      } 
  labels:
    name: schema-registry-ingress
  name: schema-registry-ingress
spec:
  rules:
  - host: schemareg.big-data2.safaricomet.net
    http:
      paths:
      - backend:
          service:
            name: schema-registry
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
