{{- if .Values.ingress.yarn.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "hadoop.fullname" . }}-yarn-ui-ingress
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: yarn-ui
  annotations: 
     ingress.kubernetes.io/rewrite-target: /
     kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.ingress.yarn.host }}
    http:
      paths:
      - path: /
        backend:
            serviceName: {{ include "hadoop.fullname" . }}-yarn-ui
            servicePort: 8088
        pathType: ImplementationSpecific
{{- end -}}