apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
   name: cvm        
   labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: cvm-
        patternType: prefix
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: cvm-
        patternType: prefix
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: cvm
        patternType: literal
        type: group
    type: simple
