---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafkaweb
  name: kafkaweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkaweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafkaweb
    spec:
      containers:
      - image: kapkiai/kafkaweb:v2
        name: kafkaweb
        resources: 
          limits:
            memory: "1000Mi"
          requests:
            memory: "500Mi"
        env:
        - name: kafka.brokerConnect
          value: 192.168.21.80:9094
        - name: kafka.isSecured
          value: "false"
        - name: kafka.saslMechanism
          value: "SCRAM-SHA-512"
        - name: kafka.securityProtocol
          value: "SASL_PLAINTEXT"
        - name: acl.aclEnabled
          value: "true"

        volumeMounts:
          - mountPath: /kaas_local_jaas.conf
            name: foo
            subPath:  kaas_local_jaas.conf
      volumes:
      - name: foo
        configMap:
          name: jaas-config
          defaultMode: 0777
          items:
            - key: "jaas.conf"
              path: "kaas_local_jaas.conf"
        
          
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafkaweb
  name: kafkaweb
spec:
  ports:
  - name: kafkaweb-9000
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: kafkaweb
  type: LoadBalancer
status:
  loadBalancer: {}
  
---
apiVersion: v1
data:
  jaas.conf: "KafkaClient {org.apache.kafka.common.security.scram.ScramLoginModule
    required username=\"admin\" password=\"Zrkz9tDNgnTA\";};"
kind: ConfigMap
metadata:
  name: jaas-config