apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "druid.name" . }}-logs
  labels:
    app: {{ template "druid.name" . }}
    chart: {{ template "druid.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  log4j2.xml: |
    <Configuration status="WARN">
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
        </Console>
      </Appenders>
      <Loggers>
        <Root level="INFO">
          <AppenderRef ref="Console"/>
        </Root>
    
        <!-- Set level="debug" to see stack traces for query errors -->
        <Logger name="org.apache.druid.server.QueryResource" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
        <Logger name="org.apache.druid.server.QueryLifecycle" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
    
        <!-- Set level="debug" or "trace" to see more Coordinator details (segment balancing, load/drop rules, etc) -->
        <Logger name="org.apache.druid.server.coordinator" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
    
        <!-- Set level="debug" to see low-level details about segments and ingestion -->
        <Logger name="org.apache.druid.segment" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
    
        <!-- Set level="debug" to see more information about extension initialization -->
        <Logger name="org.apache.druid.initialization" level="info" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
    
        <!-- Quieter logging at startup -->
        <Logger name="org.skife.config" level="warn" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
        <Logger name="com.sun.jersey.guice" level="warn" additivity="false">
          <Appender-ref ref="Console"/>
        </Logger>
      </Loggers>
    </Configuration>
    