apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: bigdata-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: bigdata-selfsigned-ca
  namespace: it-w01-bigdata
spec:
  isCA: true
  commonName: BIGDATA
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: bigdata-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1beta1
kind: Issuer
metadata:
  name: bigdata-ca-issuer
  namespace: it-w01-bigdata
spec:
  ca:
    secretName: root-secret