
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: 6d-prm-rating-cdr
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 432000000 
