{
 "title": "Druid System Monitoring",
 "description": "A Golang based exporter captures druid API metrics as well as JSON emitted metrics and converts them into Prometheus time-series format.",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Druid Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Druid Exporter",
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "<p style=\"text-align:center;\">\n    <img src=\"https://druid.apache.org/img/druid_nav.png\" height=\"80\" width=\"180\">\n</p>"
   }
  },
  {
   "title": "Druid Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(druid_health_status)" }
   ]
  },
  {
   "title": "Total Datasources",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(druid_datasource{})" }
   ]
  },
  {
   "title": "Total Segments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(druid_segment_count)" }
   ]
  },
  {
   "title": "Druid Task's Sucess Percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\"}) / count(druid_tasks_duration{}) * 100"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(count(druid_tasks_duration{task_status=\"RUNNING\"}) by (task_status), 0.1)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"FAILED\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Sucess Tasks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(druid_tasks_duration{task_status=\"SUCCESS\"}) by (task_status)",
     "legendFormat": "{{task_status}}"
    }
   ]
  },
  {
   "title": "Unloaded Segments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(sum(druid_emitted_metrics{metric_name=\"segment-loadQueue-count\"}))"
    }
   ]
  },
  {
   "title": "Unloaded Segments Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_emitted_metrics{metric_name=\"segment-loadQueue-size\"})"
    }
   ]
  },
  { "title": "JVM Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_emitted_metrics{metric_name=\"jvm-mem-used\"}[$__range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(druid_emitted_metrics{metric_name=\"jvm-pool-used\"}[$__range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Druid Datasource Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Datasource Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(druid_segment_size)" }
   ]
  },
  {
   "title": "Replicated Data Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_segment_replicated_size)"
    }
   ]
  },
  {
   "title": "Deep Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_segment_size / 1e+12) * 100"
    }
   ]
  },
  {
   "title": "Datasource Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_segment_size{}[$__range])) by (datasource_name)",
     "legendFormat": "{{datasource_name}}"
    }
   ]
  },
  {
   "title": "Datasource  Replication Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(druid_segment_replicated_size) by (datasource_name)",
     "legendFormat": "{{datasource_name}}"
    }
   ]
  },
  { "title": "Ingestion Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Ingestion Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_emitted_metrics{metric_name=\"ingest-events-processed\"}[$__range])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ingestion Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(druid_emitted_metrics{metric_name=\"ingest-kafka-lag\"}[$__range]))"
    }
   ]
  },
  { "title": "Druid Task Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Druid Task Status",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_tasks_duration) by (datasource, task_id, task_status)"
    }
   ]
  }
 ]
}