apiVersion: v2
appVersion: 3.1.0
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: ~10.2.1
description: The Apache Hive ™ data warehouse software facilitates reading, writing,
  and managing large datasets residing in distributed storage using SQL. Structure
  can be projected onto data already in storage. A command line tool and JDBC driver
  are provided to connect users to Hive.
home: https://hive.apache.org/
icon: https://hive.apache.org/images/hive_logo_medium.jpg
maintainers:
- email: mohdalmas0@gmail.com
  name: mohdalmas
name: hive
sources:
- https://github.com/apache/hive
- https://github.com/gradiant/charts
- https://github.com/big-data-europe/docker-hive
version: 0.1.3
