

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mpesa-cps-out-order-record-confirm
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 3
  config:
    retention.ms: 604800000 
