apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    prometheus-operator-validated: "true"
  labels:
    app: kube-prometheus-stack
    release: bigdata-prometheus
  namespace: bigdata-monitoring
  name: prometheus-rules-common
spec:
  groups:
    - alert: Container_CPU_Utilization_HIGH
      expr: (sum(rate(container_cpu_usage_seconds_total{namespace="et01-tkg-bigdata-prod",container!=""}[10m])) by (pod, container) / sum(container_spec_cpu_quota{namespace="et01-tkg-bigdata-prod",container!=""}/container_spec_cpu_period{namespace="et01-tkg-bigdata-prod",container!=""}) by (pod, container)) * 100 > 50
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: 'Container CPU usage for {{ $labels.pod }}'
        description: 'Container CPU usage is above 50% and  VALUE = {{ $value }}  LABELS = {{ $labels }}'
    - alert: Container_Memory_Usage_HIGH
      expr: (sum(container_memory_working_set_bytes{namespace="et01-tkg-bigdata-prod",container!=""}) BY (pod, container) / sum(container_spec_memory_limit_bytes > 0) BY (pod, container) * 100) > 50
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: 'Container Memory usage for {{ $labels.pod }}'
        description: 'Container Memory usage is above 50% and  VALUE = {{ $value }}  LABELS = {{ $labels }}'
#If any Pod goes down for 10minutes then this alert will be fired.
    - alert: InstanceDown
      # Condition for alerting
      expr: up{namespace="et01-tkg-bigdata-prod"} == 0
      for: 3m
      # Annotation - additional informational labels to store more information
      annotations:
        title: 'Pod {{ $labels.pod }} down'
        description: '{{ $labels.pod }} of job {{ $labels.job }} has been down for more than 3 minute.'
      # Labels - additional labels to be attached to the alert
      labels:
          severity: 'critical'
          
    # Storage Rules      
    - alert: PVC_RunningOutOfSpace
      expr:  kubelet_volume_stats_available_bytes{namespace="et01-tkg-bigdata-prod"} * 100 / kubelet_volume_stats_capacity_bytes{namespace="et01-tkg-bigdata-prod"} < 10
      for: 0m
      labels:
        severity: emergency
      annotations:
        summary: PVC is running out of space for (pod {{ $labels.pod }})
        description: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up very soon. Currently {{ $value | humanize }}% is available.  VALUE = {{ $value }} and  LABELS = {{ $labels }}"
 
    - alert: PVC_RunningOutOfSpace
      expr:  kubelet_volume_stats_available_bytes{namespace="et01-tkg-bigdata-prod"} * 100 / kubelet_volume_stats_capacity_bytes{namespace="et01-tkg-bigdata-prod"} < 20
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: PVC is running out of space for (pod {{ $labels.pod }})
        description: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up very soon. Currently {{ $value | humanize }}% is available.  VALUE = {{ $value }} and  LABELS = {{ $labels }}"
 
    - alert: PVC_RunningOutOfSpace
      expr:  kubelet_volume_stats_available_bytes{namespace="et01-tkg-bigdata-prod"} * 100 / kubelet_volume_stats_capacity_bytes{namespace="et01-tkg-bigdata-prod"} < 30
      for: 0m
      labels:
        severity: high
      annotations:
        summary: PVC is running out of space for (pod {{ $labels.pod }})
        description: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up very soon. Currently {{ $value | humanize }}% is available.  VALUE = {{ $value }} and  LABELS = {{ $labels }}"
 
    - alert: PVC_RunningOutOfSpace
      expr:  kubelet_volume_stats_available_bytes{namespace="et01-tkg-bigdata-prod"} * 100 / kubelet_volume_stats_capacity_bytes{namespace="et01-tkg-bigdata-prod"} < 40
      for: 0m
      labels:
        severity: medium
      annotations:
        summary: PVC is running out of space for (pod {{ $labels.pod }})
        description: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up very soon. Currently {{ $value | humanize }}% is available.  VALUE = {{ $value }} and  LABELS = {{ $labels }}"
 
    - alert: PVC_RunningOutOfSpace
      expr:  kubelet_volume_stats_available_bytes{namespace="et01-tkg-bigdata-prod"} * 100 / kubelet_volume_stats_capacity_bytes{namespace="et01-tkg-bigdata-prod"} < 50
      for: 0m
      labels:
        severity: low
      annotations:
        summary: PVC is running out of space for (pod {{ $labels.pod }})
        description: "{{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is expected to fill up very soon. Currently {{ $value | humanize }}% is available.  VALUE = {{ $value }} and  LABELS = {{ $labels }}"
 
