apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: jupyterhub-pvc-home
spec:
   accessModes:
       - ReadWriteOnce
   storageClassName: nfs-bigdata
   volumeMode: Filesystem
   resources:
       requests:
          storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: jupyterhub-pvc-srv
spec:
   accessModes:
       - ReadWriteOnce
   storageClassName: nfs-bigdata
   volumeMode: Filesystem
   resources:
       requests:
          storage: 10Gi
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
   # name: jupyterhub-pvc-soft
# spec:
   # accessModes:
       # - ReadWriteMany
   # storageClassName: nfs-bigdata
   # volumeMode: Filesystem
   # resources:
       # requests:
          # storage: 50Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
   # name: jupyterhub-pvc-python
# spec:
   # accessModes:
       # - ReadWriteMany
   # storageClassName: nfs-bigdata
   # volumeMode: Filesystem
   # resources:
       # requests:
          # storage: 50Gi
# # ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
   # name: jupyterhub-pvc-etc
# spec:
   # accessModes:
       # - ReadWriteOnce
   # storageClassName: vsphere-with-tanzu-storage-policy
   # volumeMode: Filesystem
   # resources:
       # requests:
          # storage: 5Gi