apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: plaintext
        port: 9096
        type: loadbalancer
        tls: false
      - name: saslssl
        port: 9093
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
      - name: saslplain
        port: 9094
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
      - name: tlsssl
        port: 9095
        type: loadbalancer
        tls: true
        authentication:
          type: tls
    # authorization:
      # type: simple
      # superUsers:
        # - admin
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.0"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
