apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/session-cookie-name: nifi-registry-cookie
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-XSS-protection: 1";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Access-Control-Allow-Origin: accept, content-type, authorization";

    
  labels:
    name: nifi-registry-ngress
  name: nifi-registry-ingress
  namespace: et02-tkg-bigdata-prod
spec:
  rules:
  - host: nifi-registry.big-data2.safaricomet.net
    http:
      paths:
      - backend:
          service:
            name: nifi-registry
            port:
              number: 18443
        path: /
        pathType: ImplementationSpecific
