apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: druid-test-topic
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 6
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824