# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"bigdata-cluster"},"rules":[{"apiGroups":["policy"],"resourceNames":["privileged"],"resources":["podsecuritypolicies"],"verbs":["use"]}]}
  creationTimestamp: "2022-02-23T09:44:35Z"
  name: bigdata-cluster
  resourceVersion: "3405964"
  uid: d74a660c-08c1-4842-aa50-914d4d024d75
rules:
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use