apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-hdfs-nn
  labels:
    app: {{ include "hadoop.name" . }}
    chart: {{ include "hadoop.chart" . }}
    release: {{ .Release.Name }}
    component: hdfs-nn
spec:
  ports:
  - name: thrift
    port: 9090
    protocol: TCP
  - name: thrift-ui
    port: 9095
    protocol: TCP
  - name: hbase-master
    port: 16000
    protocol: TCP
  - name: hbase-ui
    port: 16010
    protocol: TCP
  - name: phoenix
    port: 8765
    protocol: TCP
  - name: dfs
    port: 9000
    protocol: TCP
  - name: webhdfs
    port: 9870  
  - name: nn-jmx-metrics
    port: 17106
    protocol: TCP 
  - name: master-jmx
    port: 17108
    protocol: TCP 
  type: ClusterIP
  selector:
    app: {{ include "hadoop.name" . }}
    release: {{ .Release.Name }}
    component: hdfs-nn