apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: dc1-prometheus
  labels:
    app: dc1-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
subsets:
  - addresses:
      - ip: 10.3.41.54
    ports:
      - port: 9090
        name: tcp-prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: dc1-prometheus
  labels:
    app: dc1-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 9090
      name: tcp-prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dc1-prometheus
  labels:
    release: bigdata-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: dc1-prometheus
  namespaceSelector:
    matchNames:
    - bigdata-monitoring
    any: true
  endpoints:
  - port: tcp-prometheus
    interval: 15s
    path: /metrics

---
apiVersion: v1
kind: Endpoints
metadata:
  # the name here should match the name of the Service
  name: dc1-alertmanager
  labels:
    app: dc1-alertmanager
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
subsets:
  - addresses:
      - ip: 10.3.41.53
    ports:
      - port: 9093
        name: web
---
apiVersion: v1
kind: Service
metadata:
  name: dc1-alertmanager
  labels:
    app: dc1-alertmanager
    release: bigdata-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 9093
      name: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dc1-alertmanager
  labels:
    app: dc1-alertmanager
    release: bigdata-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: dc1-alertmanager
  namespaceSelector:
    matchNames:
    - bigdata-monitoring
    any: true
  endpoints:
  - port: web
    interval: 15s
    path: /metrics
