apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
   name: bigdata        
   labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: cvm-
        patternType: prefix
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: 6d-
        patternType: prefix
        type: topic

    - host: '*'
      operation: Read
      resource:
        name: my-test-topic
        patternType: literal
        type: topic

    - host: '*'
      operation: Describe
      resource:
        name: my-test-topic
        patternType: literal
        type: topic

    - host: '*'
      operation: Read
      resource:
        name: my-group
        patternType: literal
        type: group

    - host: '*'
      operation: Read
      resource:
        name: bigdata-6d-group
        patternType: literal
        type: group

    - host: '*'
      operation: Write
      resource:
        name: my-test-topic
        patternType: literal
        type: topic
        
    - host: '*'
      operation: Create
      resource:
        name: my-test-topic
        patternType: literal
        type: topic

    - host: '*'
      operation: Describe
      resource:
        name: my-test-topic
        patternType: literal
        type: topic

    type: simple
    