apiVersion: v1
data:
  webserver-secret-key: YTg4NWNlZDkxZmI3MGI5MjVmYzY3NmFiNTU0MDE3OGM=
kind: Secret
metadata:
  name: airflow-webserver-secret
  labels:
    tier: airflow
    component: webserver
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque