apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-prod
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.0"
    storage:
      type: persistent-claim
      size: 20Gi
      class: vsphere-with-tanzu-storage-policy
      deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      class: vsphere-with-tanzu-storage-policy
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  
