apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "hive.name" . }}
    app.kubernetes.io/component: hive
    {{- include "hive.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hive.name" . }}
      app.kubernetes.io/component: hive
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  serviceName: {{ .Release.Name }}-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hive.name" . }}
        app.kubernetes.io/component: hive
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: hive-metastore
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        # securityContext:
          # runAsUser: 997
          # allowPrivilegeEscalation: true
        command:
          - /bin/bash
          - /opt/hive/conf/startup.sh
        env:
        - name: HIVE_MODE
          value: "metastore"
        - name: HADOOP_USER_NAME
          value: "hive"
        - name: http_proxy
          value: http://172.24.14.197:3128
        - name: https_proxy
          value: http://172.24.14.197:3128
        - name: SPARK_MASTER_HOST
          value: hive-0
        - name: SPARK_MASTER_URL
          value: spark://hive-0:7077
        - name: HADOOP_OPTS
          value: "-Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/opt/hive/conf/client_jaas.conf"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 16010
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 16010
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2pl7ysp 
        volumeMounts:
        - mountPath: /opt/hive/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml    
        - mountPath: /opt/spark/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml   
        - mountPath: /opt/hive/conf/startup.sh
          name: hive-config
          subPath: startup.sh 
        - mountPath: /opt/spark/conf/spark-defaults.conf
          name: hive-config
          subPath: spark-defaults.conf
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
        - mountPath: /etc/krb5.conf
          name: hive-config
          subPath: krb5.conf
        - name: hive-sc
          mountPath: /tmp/key
        - name: jks-file
          mountPath: /etc/security/keytabs
        - mountPath: /opt/hive/conf/client_jaas.conf
          name: hive-config
          subPath: client_jaas.conf  
      - name: hive-server
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - /bin/bash
          - /opt/hive/conf/startup.sh
        env:
        - name: HIVE_MODE
          value: "server"
        - name: HADOOP_USER_NAME
          value: "hive"
        - name: http_proxy
          value: http://172.24.14.197:3128
        - name: https_proxy
          value: http://172.24.14.197:3128
        - name: SPARK_MASTER_HOST
          value: hive-0
        - name: SPARK_MASTER_URL
          value: spark://hive-0:7077
        - name: HADOOP_OPTS
          value: "-Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/opt/hive/conf/client_jaas.conf"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # readinessProbe:
          # httpGet:
            # path: /
            # port: 10002
          # initialDelaySeconds: 5
          # timeoutSeconds: 2
        # livenessProbe:
          # httpGet:
            # path: /
            # port: 10002
          # initialDelaySeconds: 10
          # timeoutSeconds: 2
        volumeMounts:
        - mountPath: /opt/hive/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml
        - mountPath: /opt/spark/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml          
        - mountPath: /opt/hive/conf/startup.sh
          name: hive-config
          subPath: startup.sh 
        - mountPath: /opt/spark/conf/spark-defaults.conf
          name: hive-config
          subPath: spark-defaults.conf
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
        - mountPath: /etc/krb5.conf
          name: hive-config
          subPath: krb5.conf 
        - name: hive-sc
          mountPath: /tmp/key
        - name: jks-file
          mountPath: /etc/security/keytabs
        - mountPath: /opt/hive/conf/client_jaas.conf
          name: hive-config
          subPath: client_jaas.conf 
      - name: hive-spark-master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - /bin/bash
          - /opt/spark/conf/spark-scripts.sh
        env:
        - name: SPARK_MODE
          value: "master"
        - name: HADOOP_USER_NAME
          value: "hive"
        - name: http_proxy
          value: http://172.24.14.197:3128
        - name: https_proxy
          value: http://172.24.14.197:3128
        - name: SPARK_MASTER_HOST
          value: hive-0
        - name: SPARK_MASTER_URL
          value: spark://hive-0:7077
        - name: HADOOP_OPTS
          value: "-Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/opt/hive/conf/client_jaas.conf"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        volumeMounts:
        - mountPath: /opt/hive/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml   
        - mountPath: /opt/spark/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml          
        - mountPath: /opt/hive/conf/startup.sh
          name: hive-config        
        - mountPath: /opt/spark/conf/spark-defaults.conf
          name: hive-config
          subPath: spark-defaults.conf
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
        - mountPath: /etc/krb5.conf
          name: hive-config
          subPath: krb5.conf
        - mountPath: /opt/hive/conf/client_jaas.conf
          name: hive-config
          subPath: client_jaas.conf 
        - mountPath: /opt/spark/conf/spark-scripts.sh
          name: hive-config
          subPath: spark-scripts.sh 
        # - name: hive-sc
          # mountPath: /tmp/key
        - name: jks-file
          mountPath: /etc/security/keytabs
      - name: hive-spark-worker-1
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - /bin/bash
          - /opt/spark/conf/spark-scripts.sh
        env:
        - name: SPARK_MODE
          value: "worker"
        - name: HADOOP_USER_NAME
          value: "hive"
        - name: http_proxy
          value: http://172.24.14.197:3128
        - name: https_proxy
          value: http://172.24.14.197:3128
        - name: SPARK_MASTER_HOST
          value: hive-0
        - name: SPARK_MASTER_URL
          value: spark://hive-0:7077
        - name: SPARK_EXECUTION_CORES
          value: "4"
        - name: HADOOP_OPTS
          value: "-Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/opt/hive/conf/client_jaas.conf"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8081
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 2
        volumeMounts:
        - mountPath: /opt/hive/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml  
        - mountPath: /opt/spark/conf/hive-site.xml
          name: hive-config
          subPath: hive-site.xml           
        - mountPath: /opt/hive/conf/startup.sh
          name: hive-config
          subPath: startup.sh 
        - mountPath: /opt/spark/conf/spark-defaults.conf
          name: hive-config
          subPath: spark-defaults.conf
        - name: hadoop-config
          mountPath: /opt/hadoop/etc/hadoop
        - mountPath: /etc/krb5.conf
          name: hive-config
          subPath: krb5.conf
        - mountPath: /opt/hive/conf/client_jaas.conf
          name: hive-config
          subPath: client_jaas.conf 
        - mountPath: /opt/spark/conf/spark-scripts.sh
          name: hive-config
          subPath: spark-scripts.sh 
        # - name: hive-sc
          # mountPath: /tmp/key
        - name: jks-file
          mountPath: /etc/security/keytabs
      # - name: hive-spark-worker-2
        # image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        # command:
          # - /bin/bash
          # - /opt/spark/conf/spark-scripts.sh
        # env:
        # - name: SPARK_MODE
          # value: "worker"
        # - name: HADOOP_USER_NAME
          # value: "hive"
        # - name: http_proxy
          # value: http://172.24.14.197:3128
        # - name: https_proxy
          # value: http://172.24.14.197:3128
        # - name: SPARK_MASTER_HOST
          # value: hive-0
        # - name: SPARK_MASTER_URL
          # value: spark://hive-0:7077
        # - name: SPARK_EXECUTION_CORES
          # value: "4"
        # - name: HADOOP_OPTS
          # value: "-Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/opt/hive/conf/client_jaas.conf"
        # resources:
# {{ toYaml .Values.resources | indent 10 }}
        # # readinessProbe:
        # #   httpGet:
        # #     path: /
        # #     port: 8081
        # #   initialDelaySeconds: 5
        # #   timeoutSeconds: 2
        # # livenessProbe:
        # #   httpGet:
        # #     path: /
        # #     port: 8081
        # #   initialDelaySeconds: 10
        # #   timeoutSeconds: 2
        # volumeMounts:
        # - mountPath: /opt/hive/conf/hive-site.xml
          # name: hive-config
          # subPath: hive-site.xml  
        # - mountPath: /opt/spark/conf/hive-site.xml
          # name: hive-config
          # subPath: hive-site.xml           
        # - mountPath: /opt/hive/conf/startup.sh
          # name: hive-config
          # subPath: startup.sh 
        # - mountPath: /opt/spark/conf/spark-defaults.conf
          # name: hive-config
          # subPath: spark-defaults.conf
        # - name: hadoop-config
          # mountPath: /opt/hadoop/etc/hadoop
        # - mountPath: /etc/krb5.conf
          # name: hive-config
          # subPath: krb5.conf
        # - mountPath: /opt/hive/conf/client_jaas.conf
          # name: hive-config
          # subPath: client_jaas.conf 
        # - mountPath: /opt/spark/conf/spark-scripts.sh
          # name: hive-config
          # subPath: spark-scripts.sh 
        # # - name: hive-sc
          # # mountPath: /tmp/key
        # - name: jks-file
          # mountPath: /etc/security/keytabs
      # - name: hive-spark-worker-3
        # image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        # imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        # command:
          # - /bin/bash
          # - /opt/spark/conf/spark-scripts.sh
        # env:
        # - name: SPARK_MODE
          # value: "worker"
        # - name: HADOOP_USER_NAME
          # value: "hive"
        # - name: http_proxy
          # value: http://172.24.14.197:3128
        # - name: https_proxy
          # value: http://172.24.14.197:3128
        # - name: SPARK_MASTER_HOST
          # value: hive-0
        # - name: SPARK_MASTER_URL
          # value: spark://hive-0:7077
        # - name: SPARK_EXECUTION_CORES
          # value: "4"
        # - name: HADOOP_OPTS
          # value: "-Dsun.security.krb5.debug=true -Djava.security.krb5.conf=/etc/krb5.conf -Djavax.security.auth.useSubjectCredsOnly=false -Djava.security.auth.login.config=/opt/hive/conf/client_jaas.conf"
        # resources:
# {{ toYaml .Values.resources | indent 10 }}
        # # readinessProbe:
        # #   httpGet:
        # #     path: /
        # #     port: 8081
        # #   initialDelaySeconds: 5
        # #   timeoutSeconds: 2
        # # livenessProbe:
        # #   httpGet:
        # #     path: /
        # #     port: 8081
        # #   initialDelaySeconds: 10
        # #   timeoutSeconds: 2
        # volumeMounts:
        # - mountPath: /opt/hive/conf/hive-site.xml
          # name: hive-config
          # subPath: hive-site.xml  
        # - mountPath: /opt/spark/conf/hive-site.xml
          # name: hive-config
          # subPath: hive-site.xml           
        # - mountPath: /opt/hive/conf/startup.sh
          # name: hive-config
          # subPath: startup.sh 
        # - mountPath: /opt/spark/conf/spark-defaults.conf
          # name: hive-config
          # subPath: spark-defaults.conf
        # - name: hadoop-config
          # mountPath: /opt/hadoop/etc/hadoop    
        # - mountPath: /etc/krb5.conf
          # name: hive-config
          # subPath: krb5.conf   
        # - mountPath: /opt/hive/conf/client_jaas.conf
          # name: hive-config
          # subPath: client_jaas.conf   
        # - mountPath: /opt/spark/conf/spark-scripts.sh
          # name: hive-config
          # subPath: spark-scripts.sh   
        # # - name: hive-sc
          # # mountPath: /tmp/key
        # - name: jks-file
          # mountPath: /etc/security/keytabs 
      volumes:
      - name: jks-file
        persistentVolumeClaim:
          claimName: hadoop-hadoop-hdfs-jks-pvc   
      - name: hive-sc
        secret:
          secretName: {{ include "hive.name" . }}-secret
      - name: hive-config
        configMap:
          name: {{ include "hive.name" . }}-cm
          items:
          - key: hive-site.xml
            path: hive-site.xml
          - key: spark-defaults.conf
            path: spark-defaults.conf
          - key: startup.sh
            path: startup.sh
          - key: krb5.conf
            path: krb5.conf
          - key: client_jaas.conf
            path: client_jaas.conf
          - key: spark-scripts.sh
            path: spark-scripts.sh
      - name: hadoop-config
        configMap:
          {{- if .Values.conf.hadoopConfigMap }}
          name: {{ .Values.conf.hadoopConfigMap }}
          {{- end }}
