apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: tls
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: tls

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: scram
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512

