{{- if .Values.spark_worker.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ include "spark.name" . }}
    app.kubernetes.io/component: worker
    {{- include "spark.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Release.Name }}-worker
  minReplicas: {{ .Values.spark_worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.spark_worker.autoscaling.maxReplicas }}
  metrics:
{{ toYaml .Values.spark_worker.autoscaling.metrics | indent 4 }}
{{- end }}