{{/*

 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

*/}}

{{- if .Values.broker.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "druid.broker.fullname" . }}
  labels:
    app: {{ include "druid.name" . }}
    chart: {{ include "druid.chart" . }}
    component: {{ .Values.broker.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ include "druid.broker.fullname" . }}
  replicas: {{ .Values.broker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "druid.name" . }}
      release: {{ .Release.Name }}
      component: {{ .Values.broker.name }}
  template:
    metadata:
      labels:
        app: {{ include "druid.name" . }}
        release: {{ .Release.Name }}
        component: {{ .Values.broker.name }}
      {{- with .Values.broker.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
      {{- end }}
    spec:
{{- if .Values.historical.securityContext }}
      securityContext:
{{ toYaml .Values.historical.securityContext | indent 8 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [ "broker" ]
          env:
          {{- range $key, $val := .Values.broker.config }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end}}
          envFrom:
            - configMapRef:
                name: {{ template "druid.name" . }}
          ports:
            - name: http
              containerPort: {{ .Values.broker.port }}
              protocol: TCP
          # livenessProbe:
          #   initialDelaySeconds: 60
          #   httpGet:
          #     path: /status/health
          #     port: {{ .Values.broker.port }}
          # readinessProbe:
          #   initialDelaySeconds: 60
          #   httpGet:
          #     path: /status/health
          #     port: {{ .Values.broker.port }}
          resources:
{{ toYaml .Values.broker.resources | indent 12 }}
          volumeMounts:
          - mountPath: /opt/druid/conf/druid/cluster/_common/core-site.xml
            name: hadoop-config
            subPath: core-site.xml
          - mountPath: /opt/druid/conf/druid/cluster/_common/hdfs-site.xml
            name: hadoop-config
            subPath: hdfs-site.xml
          - mountPath: /opt/druid/conf/druid/cluster/_common/log4j2.xml
            name: logs-config
            subPath: log4j2.xml
    {{- with .Values.broker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.broker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.broker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      serviceAccountName: {{.Values.serviceAccount }}
      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-hadoop
          items:
          - key: core-site.xml
            path: core-site.xml
          - key: hdfs-site.xml
            path: hdfs-site.xml
      - name: logs-config
        configMap:
          name: {{ template "druid.name" . }}-logs
          items:
          - key: log4j2.xml
            path: log4j2.xml
{{- end }}
