apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-keytab
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName: nfs-bigdata
  volumeMode: Filesystem