apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: common
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512

    password:
      valueFrom:
        secretKeyRef:
          name: common
          key: password
  authorization:
    acls:
    - host: '*'
      operation: Write
      resource:
        name: common-
        patternType: prefix
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: common-
        patternType: prefix
        type: topic
    - host: '*'
      operation: Read
      resource:
        name: common-test-cg
        patternType: literal
        type: group
        
    type: simple