kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keytab-pvc
spec:
   accessModes:
       - ReadWriteMany
   storageClassName: nfs-bigdata
   volumeMode: Filesystem
   resources:
       requests:
          storage: 1Gi
